apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../perus

# Kokeile ensin ilman tätä, jos oc apply antaa Forbidden-virheen
namespace: mkh985-dev

replicas:
  - name: react-ui
    count: 1
  - name: springboot-api
    count: 1

patches:
  - target:
      kind: PodDisruptionBudget
      name: ui-pdb
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
  - target:
      kind: PodDisruptionBudget
      name: api-pdb
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0

