# Tiivistettynä backend-config.yaml kertoo Google Cloudin kuormantasaajalle (Ingress), miten sen pitää käsitellä sovellustasi "verkon takana".
# Sen tärkein tehtävä sinun tapauksessasi on Health Checkin räätälöinti:
# Oikea polku: Kerroit Googlelle, että sovelluksesi vastaa vointikyselyihin polussa /java-api/v1/actuator/health eikä oletuspolussa /.
# Oikea portti: Kerroit, että tarkistus pitää tehdä porttiin 8090.
# Liikenteen salliminen: Ilman tätä Google luuli sovellustasi vialliseksi (koska / palautti virheen 404) ja esti liikenteen selaimesta API-podeille (virhe 502).
# Pähkinänkuoressa: Se on "ohjekirja", jolla Google Cloudin ulkoinen Load Balancer ja Kubernetes-podit saadaan ymmärtämään toisiaan, kun sovellus ei käytä vakioasetuksia.

# Jos käyttää sessionAffinity, niin meneekö ristiin sessiokannan kanssa ?
# Jos käytät sessiokantaa (kuten Redis, JDBC-session tai Spring Session), sessionAffinity ei
# mene sen kanssa ristiin, vaan ne täydentävät toisiaan.
# Tässä on kolme tärkeää huomiota siitä, miten ne toimivat yhdessä:
# Vikasietoisuus säilyy: Jos sessionAffinity ohjaa käyttäjän podille A, mutta se podi kaatuu,
# Ingress ohjaa käyttäjän podille B. Koska sinulla on sessiokanta, podi B hakee käyttäjän 
# tiedot sieltä ja homma jatkuu keskeytyksettä.
# Suorituskyky paranee: sessionAffinity auttaa hyödyntämään podien paikallista välimuistia 
# (L1-cache). Jos käyttäjä palaa aina samalle podille, podin ei tarvitse hakea aivan kaikkea 
# tietoa sessiokannasta joka kerta uudelleen.
# Tarpeellisuus: Jos sessiokantasi toimii jo täydellisesti ja sovelluksesi on täysin 
# "stateless" (eli podin paikallisessa muistissa ei säilytetä mitään tärkeää), 
# sessionAffinity ei ole välttämätön. Se on kuitenkin hyvä lisävarmistus hitaissa verkoissa 
# tai monimutkaisissa kirjautumisprosesseissa
# Yhteenvetona: Ne eivät tappele keskenään. Sessiokanta hoitaa tiedon säilyvyyden, 
# ja sessionAffinity hoitaa reitityksen tehokkuuden.

apiVersion: cloud.google.com/v1 # huom ai ehdotti muodoksi ://cloug.google.com, oli väärin
kind: BackendConfig
metadata:
  name: api-backend-config
  namespace: mktest
spec:
  # --- TIMEOUT-AJAT ---
  # Kuinka kauan Load Balancer odottaa vastausta API:lta (oletus 30s)
  timeoutSec: 60

  # --- SESSION PYSYVYYS (Sticky Sessions) ---
  # Varmistaa, että saman käyttäjän pyynnöt menevät aina samalle podille
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600 # Eväste voimassa 1 tunnin
  # --- HEALTH CHECK  ---
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    # TÄMÄ on polku, johon Spring Boot vastaa context-pathin kanssa:
    requestPath: /java-api/v1/actuator/health
    port: 8090