apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
        location /java-api/v1/ {
            # This MUST include the port 8090 and the context path
            proxy_pass http://api-service:8090/java-api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
