apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: mkh985-dev
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: api # Varmista, että api-servicellä on tämä sama label
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s

