# perus/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80       # Ulkoinen portti klusterin sisällä
      targetPort: 8080 # Pitää täsmätä nginx.conf:n 'listen' kanssa
  type: ClusterIP